version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: doomscroll_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doomscroll
    ports:
      - "5432:5432"
    volumes:
      - doomscroll_db_data:/var/lib/postgresql/data

volumes:
  doomscroll_db_data:
